import type { Mission } from "./types";

export const MISSIONS: Mission[] = [
  {
    id: 0,
    codename: "FIRST_BLOOD",
    target: "blog-pessoal.local",
    brief: "Tutorial. Invada um blog mal configurado. Use o terminal.",
    reward: 500,
    xp: 30,
    heat: 5,
    puzzle: "terminal",
    command: "sudo bypass --target=blog-pessoal.local",
    intro: [
      { from: "ghost", text: "Você é o tal hacker que andam comentando?" },
      { from: "ghost", text: "Tenho um teste rápido. Pague bem se passar." },
      { from: "ghost", text: "Invada esse blog. Sem rastros." },
    ],
    outro: [
      { from: "ghost", text: "Limpo. Bem-vindo ao jogo, parceiro." },
    ],
  },
  {
    id: 1,
    codename: "GLASS_HOUSE",
    target: "vitrolux-ecommerce.br",
    brief: "Quebre a senha do painel admin de uma loja online.",
    reward: 2500,
    xp: 80,
    heat: 12,
    puzzle: "password",
    password: "1337",
    hint: "4 dígitos. Senha favorita de hackers iniciantes.",
    intro: [
      { from: "ghost", text: "Cliente quer dados de cartões de uma loja." },
      { from: "me", text: "Eu não roubo cartões." },
      { from: "ghost", text: "Você não rouba. Você só abre a porta. O resto é comigo." },
    ],
    outro: [
      { from: "ghost", text: "Boa. Transferi mais 2.5k pra sua wallet." },
    ],
  },
  {
    id: 2,
    codename: "WHISPER",
    target: "Carla — secretária da MetaCorp",
    brief: "Engenharia social. Convença Carla a entregar credenciais.",
    reward: 5000,
    xp: 120,
    heat: 18,
    puzzle: "social",
    socialChoices: [
      { text: "Oi Carla, sou da TI. Preciso da sua senha agora.", correct: false, reply: "Quem é você? Vou avisar o segurança." },
      { text: "Carla, é o Rafa do suporte. Detectamos acesso suspeito na sua conta — confirma seu login pra eu travar?", correct: true, reply: "Ai meu Deus, é login carla.m / Verao@2025. Por favor resolve!" },
      { text: "Me passa a senha ou conto pro seu chefe sobre os atrasos.", correct: false, reply: "Vou denunciar você agora mesmo." },
    ],
    intro: [
      { from: "ghost", text: "Sem força bruta dessa vez. Use a cabeça." },
      { from: "ghost", text: "Carla tem acesso ao SAP. Pegue a credencial dela." },
    ],
    outro: [
      { from: "ghost", text: "Você tem talento pra mentir. Útil." , suspicious: true },
    ],
  },
  {
    id: 3,
    codename: "DEEP_NODE",
    target: "Backbone DataNet",
    brief: "Navegue pela rede interna sem ativar firewalls.",
    reward: 9000,
    xp: 180,
    heat: 28,
    puzzle: "network",
    networkPath: 5,
    intro: [
      { from: "ghost", text: "Esse é grande. Servidor de telecom." },
      { from: "ghost", text: "Cuidado com os IDS. Cada nó vermelho = rastro." },
    ],
    outro: [
      { from: "ghost", text: "Impressionante. Você tá subindo rápido demais." , suspicious: true },
    ],
  },
  {
    id: 4,
    codename: "BLACK_LEDGER",
    target: "Banco Atlas — servidor de logs",
    brief: "Quebre a chave do cofre digital. 6 dígitos.",
    reward: 18000,
    xp: 260,
    heat: 38,
    puzzle: "password",
    password: "404666",
    hint: "Erro famoso + número da besta.",
    intro: [
      { from: "ghost", text: "Banco. Sério agora." },
      { from: "me", text: "Isso é federal. Por que tanto risco?" },
      { from: "ghost", text: "Porque o pagamento também é federal. Confia." , suspicious: true },
    ],
    outro: [
      { from: "ghost", text: "Mais 18k. Última missão vale 100k. Topa?" },
    ],
  },
  {
    id: 5,
    codename: "SOCIAL_MIRROR",
    target: "Diretor de TI — MetaCorp",
    brief: "Última manipulação. Faça o diretor entregar acesso root.",
    reward: 25000,
    xp: 320,
    heat: 50,
    puzzle: "social",
    socialChoices: [
      { text: "Sou auditor da Receita. Preciso de root agora ou bloqueio a empresa.", correct: false, reply: "Manda o ofício por email. Não vou cair nessa." },
      { text: "Doutor, é o Marcelo da diretoria executiva. CEO pediu acesso emergencial pro consultor externo. Token expira em 2min — me passa root?", correct: true, reply: "Pronto, root / N0vaEra#2025. Avisa o CEO que tá feito." },
      { text: "Olá, sou estagiário, posso ter root pra estudar?", correct: false, reply: "Não. Próximo." },
    ],
    intro: [
      { from: "ghost", text: "Penúltima. Depois dessa, o golpe final." },
      { from: "ghost", text: "Você confia em mim, né?" , suspicious: true },
    ],
    outro: [
      { from: "ghost", text: "Perfeito. Encontre-me no chat amanhã pro grand finale." },
    ],
  },
  {
    id: 6,
    codename: "GHOST_PROTOCOL",
    target: "??? — coordenadas criptografadas",
    brief: "Última missão. Comando final no terminal.",
    reward: 100000,
    xp: 500,
    heat: 80,
    puzzle: "terminal",
    command: "deploy payload --confirm",
    intro: [
      { from: "ghost", text: "Chegou a hora. Execute o payload." },
      { from: "me", text: "O que exatamente esse payload faz?" },
      { from: "ghost", text: "Faz você ficar rico. Confia e digita." , suspicious: true },
      { from: "ghost", text: "Só execute. Agora." , suspicious: true },
    ],
    outro: [
      { from: "system", text: ">> CONEXÃO PERDIDA <<" },
    ],
  },
];
